"""added phone to patient

Revision ID: 56050da8aa8c
Revises: 26f86a20c198
Create Date: 2026-09-29 00:30:08.303432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56050da8aa8c'
down_revision: Union[str, Sequence[str], None] = '26f86a20c198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_db', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_db', 'phone')
    # ### end Alembic commands ###
